### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by BCITMike** [shirou/mqttcli#16]
Is this actually working for anyone? I get nothing but errors (and incomplete ones at that). I can't get this working on Windows 10 or Ubuntu 18.04.

```
# cat settings.json
{
  "host": "edited.iot.us-west-2.amazonaws.com",
  "port": 8883,
  "clientId": "fc06fa7a7d04438a9b98e9244cfad3a0",
  "caCert": "aws-root-ca.pem",
  "clientCert": "certificate.pem.crt",
  "privateKey": "private.pem.key"
}
```
```
# ./mqttcli sub --conf settings.json -t "dev/monitoring/30AEA40DB9E0"
ERRO[0000] Network Error : dial tcp 127.0.0.1:1883: connect: connection refused
```

```
# export MQTT_HOST="edited.iot.us-west-2.amazonaws.com"
# export MQTT_PORT="8883"
# ./mqttcli sub --conf settings.json -t "dev/monitoring/30AEA40DB9E0"
ERRO[0000] Network Error : %!s(<nil>)

**Comment by hudsonmd** [comment]
@BCITMike take a look at https://github.com/shirou/mqttcli/issues/15

Your issue is that it's not picking up the config file. You can verify this by looking at the port "1883" in your output since that is the default port for the protocol and your config set it to "8883" Same issue with the "127.0.0.1" host vs the one in your config.

Short answer, run this command prior to supplying a config
`export MQTT_HOST=""
`

**Comment by BCITMike** [comment]
Thanks, but I moved on to another app and then another project 2 months ago when I realized this project was dead.

**Comment by shirou** [comment]
yeah. Now I am not using MQTT, so no update is planned.

**Comment by shirou** [comment]
config reading order has been updated at 1e31202aa8a3f98091fe28694db2669cbc3f8999.
